export const SECTION_IDS = {
  OVERVIEW: 'overview',
  CURRENT_STATUS: 'current_status',
  BOOTH_WALL: 'booth_wall',
  BROCHURE: 'brochure',
  ENTRANCE_FLYER: 'entrance_flyer',
  EMPLOYEE_PREP: 'employee_prep',
  BOOTH_CHECKLIST: 'booth_checklist',
  ARCHITECT_LIST: 'architect_list',
  LEAD_FORM: 'lead_form',
  RAFFLE: 'raffle',
  SCREEN: 'screen',
  GRAPHIC_TASKS: 'graphic_tasks',
  SETUP_DAY: 'setup_day',
  NOTES_DECISIONS: 'notes_decisions',
};

export const STATUS = {
  DONE: 'done',
  IN_PROGRESS: 'in-progress',
  NEEDS_DECISION: 'needs-decision',
  DEFERRED: 'deferred',
  LOCKED: 'locked',
  PENDING: 'pending',
};

export const initialData = {
  // ── Workstream statuses ─────────────────────────────────────────
  workstreams: [
    {
      id: 'invite-graphic',
      label: 'Invitation Graphic',
      status: STATUS.IN_PROGRESS,
      notes: 'Being created by designer.',
    },
    {
      id: 'entrance-bag-flyer',
      label: 'Entrance Bag A4 Flyer',
      status: STATUS.IN_PROGRESS,
      notes: 'Side 2 Hebrew text being finalised.',
    },
    {
      id: 'main-brochure',
      label: 'Main Brochure Design',
      status: STATUS.IN_PROGRESS,
      notes: 'Text locked. Design with graphic designer.',
    },
    {
      id: 'architect-list',
      label: 'Architect Invitation List',
      status: STATUS.IN_PROGRESS,
      notes: 'Google Sheet being filled in.',
    },
    {
      id: 'lead-form',
      label: 'Lead Form / Follow-Up System',
      status: STATUS.DONE,
      notes: 'App live at tzviairfinal.vercel.app',
    },
    {
      id: 'raffle',
      label: 'Raffle / Lead Flow',
      status: STATUS.DONE,
      notes: 'Raffle wording done. Same flow as lead form.',
    },
    {
      id: 'screen-gif',
      label: 'Screen Content / GIF',
      status: STATUS.DONE,
      notes: 'GIF sent to graphic designer/team. Screen ordered (vertical).',
    },
    {
      id: 'employee-prep',
      label: 'Employee Prep Sheets',
      status: STATUS.DONE,
      notes: 'English PDF, Hebrew PDF, and Reminder Pages all done.',
    },
    {
      id: 'catalog-he',
      label: 'Small Square Catalog (Hebrew)',
      status: STATUS.DONE,
      notes: 'Uploaded. Folder Catalog (1).pdf',
    },
    {
      id: 'catalog-en',
      label: 'Small Square Catalog (English)',
      status: STATUS.IN_PROGRESS,
      notes: 'With graphic designer.',
    },
    {
      id: 'setup-day',
      label: 'Setup Day Plan',
      status: STATUS.DEFERRED,
      notes: 'Deferred to next week.',
    },
    {
      id: 'booth-items',
      label: 'Booth Item Procurement',
      status: STATUS.IN_PROGRESS,
      notes: 'Checklist in progress.',
    },
  ],

  // ── Booth / Wall Text ──────────────────────────────────────────
  boothWall: {
    kapaHeadline: {
      text: 'מיזוג אוויר עם צבי אייר מחזקת את המוניטין שלך',
      status: STATUS.LOCKED,
      lang: 'he',
      label: 'Top Kapa Headline',
      note: 'One top kapa / top sign. This wording is locked.',
    },
    backWall: {
      text: 'TzviAir logo only.\nExisting logo subtext only.\nClean premium brand wall.\nNo extra text.',
      status: STATUS.LOCKED,
      lang: 'en',
      label: 'Back Wall Direction',
    },
    sideWallHeadline: {
      text: 'Expert Planning.\nProfessional Installation.\nReliable Service.',
      status: STATUS.LOCKED,
      lang: 'en',
      label: 'Side Wall / Right Wall Headline (English)',
    },
    sideWallSubtext: {
      text: 'Personally guided by Tzvi.\nEnd-to-end execution.\nSolutions only TzviAir knows how to deliver.\nService only TzviAir knows how to provide.',
      status: STATUS.LOCKED,
      lang: 'en',
      label: 'Side Wall Subtext (English)',
    },
    sideWallVisual: {
      text: 'AutoCAD-style plan → swoosh transition → finished premium project photo.\n\nThe visual communicates the journey from planning/design to execution and service. Do not hard-code design choices — direction only.',
      status: STATUS.IN_PROGRESS,
      lang: 'en',
      label: 'Side Wall Visual Direction',
    },
  },

  // ── Brochure Text ──────────────────────────────────────────────
  brochure: {
    blueHeadlineEn: {
      text: 'Working with TzviAir Elevates Your Standard.',
      status: STATUS.IN_PROGRESS,
      label: 'Blue Highlight Headline (English)',
      lang: 'en',
      note: 'Being revised. Previous version: "Working with TzviAir Elevates the Standard."',
    },
    blueHeadlineHe: {
      text: '',
      status: STATUS.NEEDS_DECISION,
      label: 'Blue Highlight Headline (Hebrew)',
      lang: 'he',
      note: 'Needs Hebrew final decision. Options below in decisions tracker.',
    },
    existingHeBlueHeadline: {
      text: 'מציבים רף מקצועי חדש\nמהתכנון ועד הביצוע בשטח.',
      status: STATUS.LOCKED,
      label: 'Existing Hebrew Blue Headline (from brochure draft)',
      lang: 'he',
    },
    bottomQuoteHe: {
      text: 'לקוחות שנשארים מרוצים\nמאוד גם מהתוצאה וגם\nמהשירות למשך שנים רבות.',
      status: STATUS.LOCKED,
      label: 'Bottom Highlight Quote (Hebrew)',
      lang: 'he',
    },
    english: [
      {
        id: 'en-1',
        headline: 'Personally Led by Tzvi',
        body: 'Unlike large air conditioning companies, Tzvi remains personally involved — reviewing plans, refining solutions, supervising execution, and overseeing quality from start to finish.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-2',
        headline: 'Premium Finishing, Managed Under One Roof',
        body: 'Exceptional results happen when one company plans, coordinates, and executes the entire process. By combining air conditioning, drywall, lighting, drainage, and electrical work under one responsible team, TzviAir delivers cleaner finishes, higher ceilings, better service access, and a final result that simply cannot be achieved when multiple contractors work separately.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-3',
        headline: 'Service That Continues Long After Installation',
        body: 'At TzviAir, the relationship does not end when installation is complete. In the event of a system or installation issue, clients are never left navigating between companies — TzviAir coordinates and oversees the entire process to ensure problems are resolved quickly, professionally. Our goal is simple: clients who remain thrilled with both the result and the service for many years to come.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-4',
        headline: 'A True Anglo Client Experience',
        body: 'With over 95% of TzviAir\'s clientele coming from English-speaking communities, serving Anglo homeowners is part of who we are. Founded in Beit Shemesh and built around the needs of English-speaking clients, TzviAir offers mother-tongue English and Hebrew communication across sales, office support, planning, and service. For overseas homeowners, flexible after-hours Zoom meetings and ongoing communication provide clarity, confidence, and peace of mind — even across different time zones.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-5',
        headline: 'Making Premium Air Conditioning Possible — Even When the Apartment Wasn\'t Planned for It',
        body: 'Unlike traditional air conditioning installers who rely only on what the apartment builder prepared, TzviAir designs and executes complete integrated solutions — including drainage, electrical work, drywall, and lighting — making premium VRF systems possible while preserving ceiling height and architectural design.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-6',
        headline: 'Two Offices — Tel Aviv + Beit Shemesh',
        body: 'TzviAir\'s main office and showroom in Beit Shemesh offers clients and architects the opportunity to experience air conditioning in a way few companies can provide — exploring different systems, ceiling designs, grilles, installation methods, and real-life applications in person. For added flexibility, TzviAir also operates a secondary office in Tel Aviv, allowing convenient meetings for architects, contractors, and homeowners across the center of the country.',
        status: STATUS.LOCKED,
      },
      {
        id: 'en-7',
        headline: 'Working with TzviAir Elevates the Architect',
        body: 'An architect\'s reputation is ultimately shaped by the final experience their client receives. TzviAir helps architects deliver smoother projects, stronger execution, and premium results — creating an outcome clients remember and proudly associate with the architect who recommended it.',
        status: STATUS.LOCKED,
      },
    ],
    hebrew: [
      {
        id: 'he-1',
        headline: 'ליווי אישי על ידי צבי',
        body: 'בניגוד לחברות מיזוג גדולות, צבי, מנכ"ל החברה, נשאר מעורב באופן אישי — בודק תוכניות, מדייק פתרונות, מפקח על הביצוע, ומוודא איכות ושירות מתחילת הפרויקט ועד סופו.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-2',
        headline: 'גמר פרימיום, מנוהל תחת קורת גג אחת',
        body: 'תוצאות יוצאות דופן קורות כאשר חברה אחת מתכננת, מתאמת ומבצעת את כל התהליך. באמצעות שילוב של מיזוג, גבס, תאורה, ועבודות חשמל ואינסטלציה תחת צוות אחראי אחד, TzviAir מספקת גמר נקי יותר, תקרות גבוהות יותר, גישה טובה יותר לתחזוקה, ותוצאה סופית שפשוט לא ניתן להשיג כאשר כמה בעלי מקצוע עובדים בנפרד.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-3',
        headline: 'שירות שממשיך הרבה אחרי ההתקנה',
        body: 'ב־TzviAir, השירות לא מסתיים כאשר ההתקנה הסתיימה. במקרה של תקלה במערכת, לא תאלצו לרדוף ולהשיג שירות אצל החברות השונות.\nTzviAir מתאמת ומפקחת על כל תהליך התיקונים כדי לוודא שהבעיות נפתרות במהירות, במקצועיות ובאחריות מלאה.\nהמטרה שלנו פשוטה: לקוחות שנשארים מרוצים מאוד גם מהתוצאה וגם מהשירות למשך שנים רבות.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-4',
        headline: 'חוויית לקוח אנגלוסקסית אמיתית',
        body: 'כאשר מעל 95% מהלקוחות של TzviAir מגיעים מקהילות דוברות אנגלית, השירות ללקוחות אנגלוסקסים הוא חלק ממי שאנחנו.\nTzviAir נוסדה בבית שמש ונבנתה סביב דרישותיהם וצרכיהם של הלקוחות דוברי האנגלית, אנו מציעים תקשורת בעברית ובאנגלית לאורך המכירה, התמיכה המשרדית, התכנון והשירות.\nעבור לקוחות מחו״ל, שיחות ופגישות זום גמישות גם בשעות מאוחרות. תקשורת רציפה תורמת לכם ולהם להבנה מלאה בכל התהליך, ביטחון ושקט נפשי גם מול הפרשי שעות שונים.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-5',
        headline: 'להפוך מיזוג פרימיום לאפשרי — גם כשהדירה לא תוכננה לכך',
        body: 'בניגוד למתקיני מיזוג רגילים שמתבססים על ההכנות של הקבלן בדירה, TzviAir מתכננת ומבצעת פתרונות משולבים מלאים — כולל העברות ניקוז, עבודות חשמל וגבס, כדי לאפשר מערכות VRF פרימיום בכל דירה שהיא, תוך שמירה על גובה התקרה והעיצוב האדריכלי. מבלי להביא מספר בעלי מקצוע לדירה קודם לכן כדי לבצע את ההכנות הנדרשות.\nהפתרונות שלנו מתאימים לדירות קבלן חדשות וכן לדירות ישנות שאין בהן שום הכנה. הצוות שלנו מוכן לבצע עבורכם כל מה שיידרש.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-6',
        headline: 'שני משרדים — תל אביב + בית שמש',
        body: 'המשרד הראשי ואולם התצוגה של TzviAir בבית שמש מציעים לכם - לקוחות ואדריכלים, את האפשרות לחוות מיזוג בצורה ייחודית לנו, לראות מקרוב מערכות שונות, עיצובי תקרה, גרילים, תאורות שונות, שיטות התקנה ויישומים אמיתיים.\nהמשרד השני שלנו בתל אביב, מנגיש את האפשרות ללקוחות, אדריכלים, קבלנים ואנשי מקצוע מאיזור המרכז להפגש עם הצוות שלנו.',
        status: STATUS.LOCKED,
      },
      {
        id: 'he-7',
        headline: 'עבודה עם TzviAir מעלה את רמת האדריכל',
        body: 'המוניטין של אדריכל נבנה בסופו של דבר מהחוויה הסופית שהלקוח מקבל. TzviAir עוזרת לאדריכלים להוביל פרויקטים חלקים יותר, ביצוע חזק יותר שנותן תוצאה פרימיום — וליצור תוצאה שהלקוחות זוכרים ומשייכים בגאווה לאדריכלית.',
        status: STATUS.LOCKED,
      },
    ],
  },

  // ── Entrance Bag A4 Flyer ──────────────────────────────────────
  entranceBagFlyer: {
    side1: {
      description: 'Visual side — finished project photos and premium imagery. Content handled by graphic designer.',
      status: STATUS.IN_PROGRESS,
    },
    side2: {
      title: 'למה אדריכליות בוחרות ב־TzviAir',
      status: STATUS.IN_PROGRESS,
      items: [
        {
          id: 'f2-1',
          headline: 'חברה שאדריכליות יכולות לסמוך עליה',
          body: 'TzviAir עוזרת לאדריכליות להוביל פרויקטים חלקים יותר, ביצוע חזק יותר ותוצאה ברמת פרימיום — תוצאה שהלקוחות זוכרים ומשייכים בגאווה לאדריכלית שהמליצה עליה.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-2',
          headline: 'פתרונות לדירות מורכבות',
          body: 'TzviAir מתמחה בדירות ובבתים שלא הוכנו מראש למערכות מיזוג פרימיום — ויודעת ליצור את התשתיות הנדרשות כדי להגיע לתוצאה ברמה גבוהה.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-3',
          headline: 'ליווי אישי על ידי צבי',
          body: 'כל פרויקט מקבל מעורבות ישירה של צבי עצמו — מבדיקת תוכניות ודיוק פתרונות, ועד פיקוח על הביצוע ובקרת איכות.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-4',
          headline: 'תוצאה אדריכלית ללא פשרות',
          body: 'TzviAir יוצרת פתרונות VRF ומיזוג פרימיום תוך שמירה על גובה התקרה, תכנון התאורה, גישה לתחזוקה והחזון האדריכלי הכולל.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-5',
          headline: 'פרויקט מלא תחת קורת גג אחת',
          body: 'מיזוג, ניקוז, עבודות חשמל, גבס, תאורה וגמר — מנוהלים בצורה מקצועית על ידי חברה אחת אחראית, לתוצאה נקייה וחלקה יותר.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-6',
          headline: 'שירות שממשיך אחרי ההתקנה',
          body: 'הלקוחות לא נשארים לרדוף אחרי חברות שונות. TzviAir נשארת מעורבת, מתאמת שירות, ודואגת שהלקוח ימשיך לקבל מענה.',
          status: STATUS.IN_PROGRESS,
        },
        {
          id: 'f2-7',
          headline: 'חוויית לקוח אנגלוסקסית אמיתית',
          body: 'עם ניסיון רחב בעבודה מול לקוחות דוברי אנגלית ולקוחות מחו״ל, TzviAir מספקת תקשורת ברורה, ליווי מקצועי וחוויית לקוח חלקה יותר.',
          status: STATUS.IN_PROGRESS,
        },
      ],
      cta: {
        text: 'בקרו באולם התצוגה של TzviAir\nבואו לראות מקרוב מערכות מיזוג, עיצובי תקרה, גרילים, אפשרויות תאורה ושיטות התקנה אמיתיות.\n\nאולם תצוגה בבית שמש | פגישות בתל אביב\n02-628-8282 | info@tzviair.com',
        status: STATUS.IN_PROGRESS,
      },
    },
  },

  // ── Files ──────────────────────────────────────────────────────
  files: [
    {
      id: 'emp-en',
      name: 'TzviAir_Employee_Prep English.pdf',
      status: STATUS.DONE,
      link: null,
      notes: 'Uploaded. Done.',
    },
    {
      id: 'emp-he',
      name: 'TzviAir_Employee_Prep Hebrew.pdf',
      status: STATUS.DONE,
      link: null,
      notes: 'Uploaded. Done.',
    },
    {
      id: 'reminder',
      name: 'Reminder Pages.pdf',
      status: STATUS.DONE,
      link: null,
      notes: 'Uploaded. Done.',
    },
    {
      id: 'catalog-he',
      name: 'Folder Catalog (1).pdf',
      status: STATUS.DONE,
      link: null,
      notes: 'Hebrew small square catalog. 4 pages. Done.',
    },
    {
      id: 'catalog-en',
      name: 'Small Square Catalog (English)',
      status: STATUS.IN_PROGRESS,
      link: null,
      notes: 'With graphic designer. Not a writing/translation task.',
    },
    {
      id: 'invite-sheet',
      name: 'Architect Invitation List (Google Sheet)',
      status: STATUS.IN_PROGRESS,
      link: 'https://docs.google.com/spreadsheets/d/1herwnn--5BmdmuObQiUglDThW3IP4oe3/edit?usp=sharing&ouid=107006085279973137552&rtpof=true&sd=true',
      notes: 'Being filled in. Columns: Employee Name, Architect Name, Phone, Why Invite.',
    },
    {
      id: 'lead-app',
      name: 'Lead Follow-Up App',
      status: STATUS.DONE,
      link: 'https://tzviairfinal.vercel.app/',
      notes: 'Live. Raffle and lead form same flow.',
    },
  ],

  // ── Booth Checklist ────────────────────────────────────────────
  checklist: [
    // Certain / Must Have
    { id: 'c1', item: 'Vertical standing screen', category: 'certain', status: 'pending', assignee: '', notes: 'Already ordered.' },
    { id: 'c2', item: 'Screen stand / stable base', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c3', item: 'Power cable for screen', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c4', item: 'Extension cord', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c5', item: 'Multi-plug / power strip', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c6', item: 'Video file / GIF for screen', category: 'certain', status: 'pending', assignee: '', notes: 'GIF sent to team.' },
    { id: 'c7', item: 'Backup copy of screen media (USB)', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c8', item: 'iPad for lead form', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c9', item: 'iPad charger', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c10', item: 'Internet solution / hotspot backup', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c11', item: 'Printed brochures', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c12', item: 'Entrance bag flyers (A4)', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c13', item: 'Small square picture brochures', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c14', item: 'Business cards', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c15', item: 'Lead form / raffle flow (app access)', category: 'certain', status: 'pending', assignee: '', notes: 'tzviairfinal.vercel.app' },
    { id: 'c16', item: 'Table or counter', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c17', item: 'Chairs (if approved)', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c18', item: 'Brochure holder / display stand', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c19', item: 'Branded table surface or clean table cover', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c20', item: 'Kapa sign (top headline)', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c21', item: 'Back wall logo graphic', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c22', item: 'Right wall process graphic', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c23', item: 'Tape / zip ties / Velcro / mounting supplies', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c24', item: 'Scissors / utility knife', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c25', item: 'Pens', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c26', item: 'Staff name tags', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c27', item: 'Water / snacks for staff', category: 'certain', status: 'pending', assignee: '', notes: '' },
    { id: 'c28', item: 'Staff prep sheets / A5 reminders', category: 'certain', status: 'pending', assignee: '', notes: '' },
    // Maybe needed
    { id: 'c29', item: 'Small branded giveaway', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c30', item: 'Small sign: "Visit our showroom"', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c31', item: 'QR code sign for lead form', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c32', item: 'QR code backup printed cards', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c33', item: 'Extra lighting (if booth lighting is weak)', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c34', item: 'Portable battery pack', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c35', item: 'Extra phone charger', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c36', item: 'Cleaning wipes', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c37', item: 'Small trash bag', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c38', item: 'Folder for collected cards/papers', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c39', item: 'Clipboard', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c40', item: 'Spare printed staff schedule', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c41', item: 'Small raffle explanation card', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c42', item: 'Small "Ask us about architect partnerships" card', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c43', item: 'Display stand for square picture brochure', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c44', item: 'Extra screen adapter / HDMI cable', category: 'maybe', status: 'pending', assignee: '', notes: '' },
    { id: 'c45', item: 'Backup laptop or USB media player', category: 'maybe', status: 'pending', assignee: '', notes: '' },
  ],

  // ── Graphic Designer Tasks ─────────────────────────────────────
  graphicTasks: [
    {
      id: 'gt1',
      task: 'Main brochure design',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'All 7 English + 7 Hebrew sections text locked. Design in progress.',
    },
    {
      id: 'gt2',
      task: 'Small square catalog — English version',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'Hebrew version done (Folder Catalog (1).pdf). English with designer.',
    },
    {
      id: 'gt3',
      task: 'Invitation graphic',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'Being created.',
    },
    {
      id: 'gt4',
      task: 'Entrance bag A4 flyer — Side 1 visual layout',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'Side 1 is visual/photos. Side 2 text being finalised.',
    },
    {
      id: 'gt5',
      task: 'Entrance bag A4 flyer — Side 2 Hebrew text layout',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'Working text ready in dashboard. Awaiting final approval before design.',
    },
    {
      id: 'gt6',
      task: 'Screen GIF / vertical video',
      status: STATUS.DONE,
      priority: 'medium',
      notes: 'Sent to team. Screen standing vertically.',
    },
    {
      id: 'gt7',
      task: 'Kapa sign design',
      status: STATUS.IN_PROGRESS,
      priority: 'high',
      notes: 'Text locked: מיזוג אוויר עם צבי אייר מחזקת את המוניטין שלך',
    },
    {
      id: 'gt8',
      task: 'Back wall graphic (logo + subtext)',
      status: STATUS.IN_PROGRESS,
      priority: 'medium',
      notes: 'Logo only, existing subtext only. Clean brand wall.',
    },
    {
      id: 'gt9',
      task: 'Right wall process graphic',
      status: STATUS.IN_PROGRESS,
      priority: 'medium',
      notes: 'AutoCAD plan → swoosh → finished project. English headline + subtext locked.',
    },
  ],

  // ── Decisions ─────────────────────────────────────────────────
  decisions: [
    {
      id: 'dec-brochure-blue-he',
      question: 'Which Hebrew version for the brochure blue highlight headline?',
      options: [
        'עבודה עם TzviAir מעלה את הסטנדרט שלך',
        'עבודה עם TzviAir מעלה את הרף שלך',
        'Keep existing: מציבים רף מקצועי חדש / מהתכנון ועד הביצוע בשטח.',
        'Other (add in notes)',
      ],
      selected: null,
      status: STATUS.NEEDS_DECISION,
      notes: '',
      lang: 'he',
    },
    {
      id: 'dec-chairs',
      question: 'Are chairs approved for the booth?',
      options: ['Yes — bring chairs', 'No — standing only'],
      selected: null,
      status: STATUS.NEEDS_DECISION,
      notes: '',
      lang: 'en',
    },
    {
      id: 'dec-giveaway',
      question: 'Small branded giveaway — include or skip?',
      options: ['Include — decide what', 'Skip for this expo'],
      selected: null,
      status: STATUS.NEEDS_DECISION,
      notes: '',
      lang: 'en',
    },
    {
      id: 'dec-flyer-side2-final',
      question: 'Is the entrance bag flyer Side 2 Hebrew text approved for the designer?',
      options: ['Approved — send to designer', 'Needs more changes'],
      selected: null,
      status: STATUS.NEEDS_DECISION,
      notes: '',
      lang: 'he',
    },
  ],

  // ── Notes ─────────────────────────────────────────────────────
  notes: [],

  // ── Employee prep content ──────────────────────────────────────
  employeePrep: {
    mainMessage: 'Working with TzviAir strengthens the architect\'s name.',
    philosophy: 'The expo is not only about handing out brochures or collecting phone numbers. The goal is to present TzviAir as a boutique air conditioning company that architects can trust with their clients, projects, and professional reputation.',
    doNotSay: [
      'Cheapest / price as opening topic',
      'Just installers',
      'HVAC (do not use this word)',
      'Commission as an opening topic',
      'Too technical at the start',
      'Aggressive competitor talk',
    ],
    commissionWording: 'Do not open with "commission." Say: "We believe in long-term, win-win relationships. If the cooperation is serious and worthwhile, we definitely will take care of you."',
  },
};
